// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icsttnftxcfgnwhifsdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imljc3R0bmZ0eGNmZ253aGlmc2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTMyNDIsImV4cCI6MjA3MzM2OTI0Mn0.bJHBOpE5YztWHvJse4CG7z2C_e0cQFBzZbK8HGy0Q2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});